### ISSUE TITLE
Metada version mis match on 2.2.0 version 

### ISSUE THREAD

**Issue by BalamChaac** [dimpu/ngx-md#111]
The console says:

ERROR in Error: Metadata version mismatch found version 4, expected 3 on the angular2-markdown module

**Comment by dimpu** [comment]
@BalamChaac I just pushed a new version of npm please check it now. If you still have the same issue. Let us know. A screen would be great.

**Comment by yiu31802** [comment]
Hello, I am also observing this issue. (Angular 4.4.6, ng2-markdown 2.2.0/2.2.2, ) I doubt this is related to compiler versions of Angular.

However strangely, when I keep the compiler running and modify any text so that the compiler detect changes, the result is success and the application is indeed running fine.

That's an annoying behaviour and I really wish it succeeds without an initial failure.

**Comment by dimpu** [comment]
Can anyone please upload a screenshot or plunker. I don't see that issue in any of my apps. Also please post your package.json

**Comment by Eraldo** [comment]
I too get a metadata version mismatch error.
`Error: Metadata version mismatch for module /project/node_modules/angular2-markdown/markdown/markdown.service.d.ts, found version 4, expected 3`

I am using:
`"angular2-markdown": "^2.2.2"`
`"@angular/...": "^4.4.6"`

**Comment by Eraldo** [comment]
the package version was still set to 2.2.0
If you deploy using a script that auto-increments.. then making sure that the release version and the package.json version are in sync.

**Comment by ninjadq** [comment]
I also have the same issue.

package.json
```
"dependencies": {
        "@angular/animations": "^4.3.0",
        "@angular/common": "^4.3.0",
        "@angular/compiler": "^4.3.0",
        "@angular/compiler-cli": "^4.3.0",
        "@angular/core": "^4.3.0",
        "@angular/forms": "^4.3.0",
        "@angular/http": "^4.3.0",
        "@angular/platform-browser": "^4.3.0",
        "@angular/platform-browser-dynamic": "^4.3.0",
        "@angular/router": "^4.3.0",
        "@ngx-translate/core": "^6.0.0",
        "@ngx-translate/http-loader": "0.0.3",
        "@types/jquery": "^2.0.41",
        "@webcomponents/custom-elements": "^1.0.0",
        "angular2-markdown": "2.2.0",
        "clarity-angular": "^0.10.17",
        "clarity-icons": "^0.10.17",
        "clarity-ui": "^0.10.17",
        "core-js": "^2.4.1",
        "harbor-ui": "0.6.2",
        "intl": "^1.2.5",
        "mutationobserver-shim": "^0.3.2",
        "ngx-cookie": "^1.0.0",
        "rxjs": "^5.0.1",
        "ts-helpers": "^1.1.1",
        "web-animations-js": "^2.2.1",
        "zone.js": "^0.8.4"
    },
    "devDependencies": {
        "@angular/cli": "^1.0.0",
        "@angular/compiler-cli": "^4.3.0",
        "@types/core-js": "^0.9.34",
        "@types/jasmine": "~2.2.30",
        "@types/node": "^6.0.42",
        "bootstrap": "4.0.0-alpha.5",
        "codelyzer": "~2.0.0-beta.4",
        "enhanced-resolve": "^3.0.0",
        "jasmine-core": "2.4.1",
        "jasmine-spec-reporter": "2.5.0",
        "karma": "1.2.0",
        "karma-cli": "^1.0.1",
        "karma-jasmine": "^1.0.2",
        "karma-mocha-reporter": "^2.2.1",
        "karma-remap-istanbul": "^0.2.1",
        "protractor": "4.0.9",
        "rollup": "^0.41.6",
        "rollup-plugin-commonjs": "^8.0.2",
        "rollup-plugin-node-resolve": "^3.0.0",
        "rollup-plugin-uglify": "^1.0.1",
        "ts-node": "1.2.1",
        "tslint": "^4.1.1",
        "typescript": "~2.2.0",
        "typings": "^1.4.0",
        "webdriver-manager": "10.2.5"
    }
```

console result

```
Error: Metadata version mismatch for module /Users/dengq/Work/harbor/src/ui_ng/lib/node_modules/angular2-markdown/markdown/markdown.service.d.ts, found version 4, expected 3
    at StaticSymbolResolver.getModuleMetadata (/Users/dengq/Work/harbor/src/ui_ng/lib/node_modules/@angular/compiler/bundles/compiler.umd.js:25616:34)
    at StaticSymbolResolver._createSymbolsOf (/Users/dengq/Work/harbor/src/ui_ng/lib/node_modules/@angular/compiler/bundles/compiler.umd.js:25404:46)
    at StaticSymbolResolver.getSymbolsOf (/Users/dengq/Work/harbor/src/ui_ng/lib/node_modules/@angular/compiler/bundles/compiler.umd.js:25385:14)
    at /Users/dengq/Work/harbor/src/ui_ng/lib/node_modules/@angular/compiler/bundles/compiler.umd.js:24241:30
    at Array.forEach (<anonymous>)
    at extractProgramSymbols (/Users/dengq/Work/harbor/src/ui_ng/lib/node_modules/@angular/compiler/bundles/compiler.umd.js:24240:79)
    at AotCompiler.analyzeModulesAsync (/Users/dengq/Work/harbor/src/ui_ng/lib/node_modules/@angular/compiler/bundles/compiler.umd.js:23796:47)
    at CodeGenerator.codegen (/Users/dengq/Work/harbor/src/ui_ng/lib/node_modules/@angular/compiler-cli/src/codegen.js:32:14)
    at codegen (/Users/dengq/Work/harbor/src/ui_ng/lib/node_modules/@angular/compiler-cli/src/main.js:13:81)
    at Object.main (/Users/dengq/Work/harbor/src/ui_ng/lib/node_modules/@angular/tsc-wrapped/src/main.js:106:16)
Compilation failed
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

**Comment by yiu31802** [comment]
just an update from my side but, I upgraded the angular version of my app to 5.0 entirely and this issue simply disappeared.
